#!/bin/sh
# Start/stop the SMS injectd.

### BEGIN INIT INFO
# Provides:          sms_injectd
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Should-Start:      $network
# Should-Stop:       $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: SMS injectd
# Description:       web server for SMS injecting
### END INIT INFO

. /lib/lsb/init-functions

DAEMON=/opt/gammu/sbin/sms_injectd.py
INJECTPATH=/opt/gammu/bin/gammu-smsd-inject
PATHSECRET=/opt/gammu/etc/gammu/sms_secret.list

CONFIG=/opt/gammu/etc/gammu/gammu.conf
ALLOWED=/opt/gammu/etc/gammu/allowed_ips.list
INJECTMATCH=/opt/gammu/etc/gammu/inject_matches.list

PIDFILE=/opt/gammu/var/run/sms_injectd.pid
HOMEDIR=/opt/gammu/var/log/gammu

LOGDIR=/opt/gammu/var/log/gammu
LOGFILE=/opt/gammu/var/log/gammu/sms_injectd.log

ADDRESS=127.0.0.1
PORT=9045

test -x $DAEMON || exit 0
test -x $INJECTPATH || exit 0


case "$1" in
  start)
    log_daemon_msg "Starting SMS injectd"
    log_progress_msg "sms_injectd"

    if [ ! -d $LOGDIR ] ; then
        mkdir -p $LOGDIR
        chown sms-gateway:root $LOGDIR
    fi

    start-stop-daemon --start --quiet --pidfile $PIDFILE \
        --startas $DAEMON -- -c $CONFIG -r $ALLOWED -i $PIDFILE -d -f -u sms-gateway -g dialout \
        -h $HOMEDIR -l $LOGFILE -s $INJECTPATH -e $PATHSECRET -m $INJECTMATCH -a $ADDRESS -p $PORT || true

    log_end_msg 0
    ;;

  stop)
    log_daemon_msg "Stopping SMS injectd"
    log_progress_msg "sms_injectd"
    start-stop-daemon --stop --quiet \
        --pidfile $PIDFILE || true

    log_end_msg 0
    ;;

  reload)
    # We don't have support for this yet.
    exit 1
    ;;

  restart|force-reload)
    $0 stop
    sleep 1
    $0 start
    ;;

  *)
    echo "Usage: $0 {start|stop|restart|force-reload}"
    exit 1

esac

exit 0
